### ISSUE TITLE
b-Profil Sayfası-Topluluklar Sekmesi-Başvuru Durumu

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#109]
- [ ] Bir topluluk için başvuru yapıldıktan sonra "Başvuru Yapılan Topluluklar" altında gösterilen başvurular için, ilgili topluluk yöneticisinin başvuruyu "Red Etmesi" durumunda başvurunun reddedildiği ve nedeni kullanıcıya bildirilmelidir.

**Comment by baldemir** [comment]
duplicate of #111
