### ISSUE TITLE
i-Etkinlik Ekle-Onay Sayfası Eksik

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#116]
- [ ] Bir "Topluluk Yöneticisi" tarafından oluşturulan etkinliğin, sistem güvenliği için "Sistem Yöneticisi" tarafından onaylandıktan sonra yayına alınması sağlanmalıdır.

**Comment by kemalsami** [comment]
Etkinlikler sistem yöneticisi tarafından onay beklemektedir
