### ISSUE TITLE
Guppy v.1.0.8.16 - Etkinlik fotosu ve Profil fotosu 1.3 Mb dan olan fotolar eklenemiyor 

### ISSUE THREAD

**Issue by cskaraca** [GuppyEvents/guppy_events#132]
Topluluklar etkinlik ekleyememe şikayetlerinde bulunmuş ve yapılan denemeler sonucu dedikleri gibi gerek etkinlik fotosu eklerken gerekse profil fotosu eklediklerinde boyutu 1 Mb dan büyük olan fotolar yüklenmeye çalışıldığında "413 Request Entity Too Large"(ngix/1.10.0 (ubuntu))  gibi hatalar gözlenmiştir acilen bu durumun düzeltilmesi gerekmektedir.

**Comment by baldemir** [comment]
Sınır 3 MB'a çıkarıldı.
