### ISSUE TITLE
Guppy v.1.0.8.19 - Kayıt yaptıran kişiye mailinize aktivasyon mailini onaylaması gerektiği bilgisi

### ISSUE THREAD

**Issue by cskaraca** [GuppyEvents/guppy_events#137]
Facebook üzerinden kayıt yaptırmayan kullanıcılar  yani normal yolla kayıt yaptıranlar  kulüplere üye olabilmek için aktivasyon mailinin onaylaması gerektiğini bilemeyebilir .

**Comment by Shathra** [comment]
Uyarı mesajı her sayfada çıkacak şekilde güncellendi.
