### ISSUE TITLE
Guppy v.1.0.8.20 - Arama Çubuğu düzgün çalışmıyor !!!!

### ISSUE THREAD

**Issue by cskaraca** [GuppyEvents/guppy_events#139]
Briç kulübü başkanı arama çubuğunda kendilerini aradığında çıkmadığını iletti ve bunun üzerine arama çubuğunda yaptığım testler sonucu gelen şikayetin doğru olduğu , denemeler sonucunda ultimate frisbee kulübünün de arama çubuğuna ul yazdığımda çıkmadığı gözlemlenmiştir. ( Fakat ilginç bir şekilde fr yazdığında çalışıyor ). Arama çubuğuna q yazdığımda Quidditch topluluğu çıkmıyor. Bu hatanın acil şekilde düzeltilmesinde fayda bulunmaktadır

**Comment by Shathra** [comment]
Bu sorun topluluğun bir admini olmaması ve/veya eventi olmaması sebebiyle kaynaklanıyordu. Düzeltilmiş olması lazım, tekrar kontrol edilmesinde fayda var. (Özellikle katılımcı sayısı ve event sayısı değerlerinin doğru olduğu kontrol edilebilir)

**Comment by cskaraca** [comment]
Selçukcum sorunun o kaynaklı olduğunu düşünmüyorum , çünkü  belirttiğim gibi Ultimate Frisbee kulübünü aramak isteynler , ul yazınca bulamıyor ,ama fr yazınca çıkıyor.  Peki sorun şimdi kesin çözüldü mü ??

**Comment by kemalsami** [comment]
arama işlemi direk kelime odaklı olduğundan (mysql like kullanıldığından) ul yazılması durumunda bütün kulüplerde topluluk olduğundan topluluk kelimesiinin ul sini bulmaktadır. Bu sebepten ulti yazılırsa problemin çözüldüğü görülecektir. 

Ayrıca ileriki aşamalarda daha iyi bir search mekanizması (elastic search) kullanılacağından böyle bir problem olmayacaktır
