### ISSUE TITLE
Guppy v.1.0.8 - Versiyon Numaraları

### ISSUE THREAD

**Issue by Shathra** [GuppyEvents/guppy_events#141]
Şu an issue'ları açan o issue'nun hangi sürümde ortaya çıktığını belirtemiyor. Issue'ları açan, çözen ve deploy edenlerin issue'ların hangi versiyonda görüldüğü, çözüldüğü ve deploy edip edilmediğini görmek amacıyla sistemin her deploy edilişinde otomatik veya manuel olarak versiyon bilgisi girilmeli. Bu bilgi site üzerinden kullanıcının gözünün önünde olmayan bir yerden ulaşılabilmeli (Örnek javascript'ten version() fonksiyonu çalıştırmak veya seruvent.com/version.txt adresine girmek gibi)

**Comment by kemalsami** [comment]
seruvent.com/version altında version numarası bulunmaktadır. Deploy edilmesi ile 1.0.8 version gözükecektir.
