### ISSUE TITLE
b-Arama Sonuçları-Etkinlikler

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#16]
Arama tamamlandıktan sonra "Etkinlikler" başlığı altında sunulan sonuçlardan biri tıklandığında ilgili etkinliğin detay sayfasına yönlendirme yapılmalıdır.

Şu an default olarak "Arama" sayfasına yönlendiriliyor.

**Comment by kemalsami** [comment]
Düzeltildi...
