### ISSUE TITLE
b-Kayıt-Genel

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#35]
Kayıt işlemi sırasında oluşturulan şifreyi doğrulamak amacıyla tekrar giriş yaptığımız "Şifre Tekrar" alanında aynı şifre girilmezse şifrelerin uyuşmadığı uyarısı verilmeli ve düzeltilmesi beklenmelidir.

**Comment by kemalsami** [comment]
Kayıt butonu tıklanmadan önce şifrelerin kontrolü sağlanıyor
