### ISSUE TITLE
Guppy v.1.0.7.34 - Etkinlik Detay Sayfası-Genel

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#44]
"Register" butonunun Türkçe olarak (katıl,kayıt ol vb.) sunulması sağlanmalıdır.
Butonun işlevi tanımlanmalıdır.
"Takvime ekle" linkinin işlevi tanımlanmalıdır. 

Her iki işlev için de "Kulüp Detay Sayfası"nda bulunan "Yönetici Ol" butonu için yapılacak olan hesap giriş kontrol akışı sağlanmalıdır.

**Comment by sawer1905** [comment]
Bu maddenin sistem bütünlüğü açısından kritik olduğu düşüncesindeyim, katılıyorsanız önceliğini arttıralım derim.

**Comment by kemalsami** [comment]
Takvime ekle butonu kaldırıldı. İşlevsel olarak zaten etkinliği takip etme ile aynı olduğu sonucuna varıldı
