### ISSUE TITLE
b-Çok Yakında Sayfası-Abone Olun

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#58]
Sayfada bulunan "Abone Olun" butonuna tıklandığında açılan form doldurulurken "reCaptcha" alanı işaretlenmeden "Kayıt" butonuna basılırsa form kapatıldıktan sonra alanın işaretlenmediği bilgisi verildiği için doldurulan tüm alanların tekrar doldurulması gerekiyor.

**Comment by kemalsami** [comment]
Bu işlem üzerinde uzun durulmayacak çünkü production ortamına yakın zamanda (20.02.2017) çıkılacak ve bu sayfa kullanılmayacak
