### ISSUE TITLE
b-Kulüpler Sayfası-Genel

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#59]
Listelenen herhangi bir kulübün altında bulunan facebook, twitter veya instagram paylaşma butonları tıklandıktan sonra tıklanılan buton, sayfanın herhangi bir alanına tekrar tıklanıncaya kadar görünmüyor.

Paylaşma butonu tıklandığında ilgili paylaşım platformuna yönlendirilme yapılması gerekiyor.

**Comment by sawer1905** [comment]
Bu madde ile ilgili olarak, eğer bir kulüp için facebook,twitter ya da instagram sayfası bilgisi girilmemişse sosyal medya butonuna basıldığında yeni pencerede Kulüpler sayfası açılıyor bunun yerine kullanıcıya "kulüp instagram/facebook/twitter sayfası bulunmamaktadır/girilmemiştir" şeklinde bir uyarı verilse daha iyi olur diye düşünüyorum.

**Comment by baldemir** [comment]
ikinci yorum yapıldı.
