### ISSUE TITLE
Guppy v.1.0.7.49 -Topluluk Üyeler Sayfası Başvuru Hatası

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#60]
Daha önce başvuru yapılması durumunda sayfada bulunan kulüp arkaplanının altında "Başvurdunuz" bilgisi görünmesine rağmen alt kısımda bulunan topluluk üyelerinin listelendiği alanda "Topluluğa Katıl" butonu görüntülenmektedir. Bu butonun daha önce başvuru yapıldıysa görüntülenmemesi gerekmektedir.

**Comment by kemalsami** [comment]
Button kullanım şekli değiştiğinden butonun kendisi kaldırılarak çözüldü
