### ISSUE TITLE
b-Profil Sayfası-Mail Adresleri Sekmesi

### ISSUE THREAD

**Issue by sawer1905** [GuppyEvents/guppy_events#63]
Eklenmiş olan mail adreslerininin listelendiği bu alanda her mail adresi için satırın sonunda bulunan "İşlem" butonuna tıklandığında "Kaydet", "Aktivasyon Linki" ve "Sil" seçenekleri bulunmaktadır.

"Kaydet" seçeneği için öncelikle değişikliğin yapılmasına imkan sunulmalıdır.
Kaydet" ve "Aktivasyon Linki" seçeneklerinin ilgili işlemleri gerçekleştirmesi sağlanmalıdır.

**Comment by kemalsami** [comment]
Kaydet butonu kaldırıldı ve linkler ikonik hale getirildi
