### ISSUE TITLE
Guppy v.1.0.7.75 - Topluluk Sayfası Beğen&Paylaş Butonu

### ISSUE THREAD

**Issue by kemalsami** [GuppyEvents/guppy_events#97]
- [x] Topluluk sayfasında bulunan beğen butonu çalışır hale getirilmeli ya da kaldırılmalıdır
- [x] Topluluk sayfasında bulunan paylaş butonu ile topluluk facebook ve twitter üzerinden paylaşılabilmelidir

**Comment by Shathra** [comment]
Like butonu kaldırıldı, paylaş butonu twitter ve facebook paylaş ikonları ile değiştirildi, çalışır duruma getirildi.
